import json

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

import report_builder as rb

st.set_page_config(
    page_title="PolyMarket Weather Data Explorer",
    layout="wide",
    initial_sidebar_state="expanded",
)


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------
# NOTE (2026-08 redesign): the evaluated CSV is fully regenerated by
# settle_outcomes.py on every settlement run, and now carries the fixed
# schema (see SCHEMA.md). Historical rows recovered from the legacy
# mixed-schema log will have NaN in columns that didn't exist yet when
# they were logged (gfs_bucket, market_modal_bucket, national_model_*,
# etc.) -- this is expected and handled throughout below, not a bug.
@st.cache_data(ttl=60)
def load_data():
    df = pd.read_csv("polymarket_weather_evaluated.csv")
    return df


df = load_data()

st.title("☀️ Weather Market Data Explorer")
st.caption(
    "Raw forecast/market observations and settlement backtesting. "
    "This dashboard is descriptive, not a trading signal."
)

if df.empty:
    st.warning("No data yet in polymarket_weather_evaluated.csv.")
    st.stop()


# ---------------------------------------------------------------------------
# Sidebar controls
# ---------------------------------------------------------------------------
st.sidebar.header("Controls")
if st.sidebar.button("🔄 Force Refresh Data"):
    st.cache_data.clear()
    st.rerun()

st.sidebar.divider()
st.sidebar.header("Filters")

# Legacy rows (recovered from the original mixed-schema log, or the
# pre-fix "gen_d" enhanced schema) predate the 2026-08 audit fixes:
# lead_time_hours used UTC midnight instead of local midnight, forecast
# coordinates were city-center instead of settlement-station-precise,
# and ecmwf_bucket/gfs_bucket/market_modal_bucket didn't exist yet.
# They're genuine historical data, not corrupted -- but if you want a
# "clean" view using only rows collected after the fixes, use this
# toggle rather than deleting anything from the underlying files.
LEGACY_SCHEMA_TAGS = {"gen_a", "gen_b", "gen_c", "gen_d", "1", 1}
exclude_legacy = st.sidebar.checkbox(
    "Exclude pre-fix rows (legacy schema)",
    value=False,
    help=(
        "Hides rows recovered from the original mixed-schema log and "
        "the pre-audit 'gen_d' schema. Nothing is deleted -- this only "
        "changes what this dashboard view shows."
    ),
)
if exclude_legacy and "_schema_version" in df.columns:
    before = len(df)
    df = df[~df["_schema_version"].astype(str).isin({str(v) for v in LEGACY_SCHEMA_TAGS})]
    st.sidebar.caption(f"Showing {len(df)} of {before} rows (post-fix schema only).")
elif exclude_legacy:
    st.sidebar.caption("No _schema_version column found in this data -- toggle has no effect.")

all_cities = sorted(df["city"].dropna().unique())
selected_cities = st.sidebar.multiselect(
    "Cities", options=all_cities, default=all_cities
)

target_dates = sorted(df["target_date"].dropna().unique(), reverse=True)
target_date = st.sidebar.selectbox("Target Date (for Live Snapshot tab)", options=target_dates)

df = df[df["city"].isin(selected_cities)] if selected_cities else df

st.sidebar.divider()
st.sidebar.caption("Field definitions & known limitations: see SCHEMA.md in the repo.")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def has_col(frame, col):
    return col in frame.columns


def fmt_pct(x):
    return "—" if pd.isna(x) else f"{x * 100:.1f}%"


def fmt_c(x):
    return "—" if pd.isna(x) else f"{x:.1f}°C"


tab_live, tab_backtest, tab_reliability, tab_quality, tab_report = st.tabs(
    ["📍 Live Snapshot", "📈 Backtesting", "🏆 Model Reliability", "🧪 Data Quality", "📄 Performance Report"]
)


# ===========================================================================
# TAB: Live Snapshot
# ===========================================================================
with tab_live:
    df_active = df[df["target_date"] == target_date].copy()
    if df_active.empty:
        st.info("No observations logged yet for this target date.")
    else:
        latest = (
            df_active.sort_values("timestamp_utc").groupby("city").last().reset_index()
        )

        col1, col2, col3, col4 = st.columns(4)
        col1.metric("Cities Tracked", len(latest))
        col2.metric(
            "Avg Model Spread (|ECMWF−GFS|)",
            fmt_c(latest["abs_model_spread_c"].mean())
            if has_col(latest, "abs_model_spread_c")
            else "—",
        )
        col3.metric(
            "Avg Market Implied Temp",
            fmt_c(latest["market_implied_temp_c"].mean())
            if has_col(latest, "market_implied_temp_c")
            else "—",
        )
        flagged = (
            (latest["data_quality"] != "OK").sum()
            if has_col(latest, "data_quality")
            else 0
        )
        col4.metric("Rows w/ Data Quality Flags", int(flagged))

        st.subheader("Forecast vs. Market, by City")
        display_cols = {
            "city": "City",
            "ecmwf_max_c": "ECMWF (°C)",
            "ecmwf_bucket": "ECMWF Bucket",
            "ecmwf_bucket_probability": "Mkt Price of ECMWF Bucket",
            "gfs_max_c": "GFS (°C)",
            "gfs_bucket": "GFS Bucket",
            "gfs_bucket_probability": "Mkt Price of GFS Bucket",
            "icon_max_c": "ICON (°C)",
            "icon_bucket": "ICON Bucket",
            "icon_bucket_probability": "Mkt Price of ICON Bucket",
            "national_model_name": "National Model",
            "national_model_max_c": "National Model (°C)",
            "national_model_bucket": "National Model Bucket",
            "national_model_bucket_probability": "Mkt Price of National Model Bucket",
            "model_spread_c": "ECMWF-GFS Spread (°C)",
            "market_modal_bucket": "Market Favorite Bucket",
            "market_modal_bucket_price": "Favorite Bucket Price",
            "market_implied_temp_c": "Market Implied Temp (°C)",
            "lead_time_hours": "Lead Time (h, to day start)",
            "hours_to_resolution": "Hours to Resolution (to day end)",
            "data_quality": "Data Quality",
        }
        available = [c for c in display_cols if c in latest.columns]
        missing = [c for c in display_cols if c not in latest.columns]

        table = latest[available].rename(columns=display_cols)
        st.dataframe(
            table,
            column_config={
                "ECMWF (°C)": st.column_config.NumberColumn(format="%.1f °C"),
                "GFS (°C)": st.column_config.NumberColumn(format="%.1f °C"),
                "ICON (°C)": st.column_config.NumberColumn(format="%.1f °C"),
                "National Model (°C)": st.column_config.NumberColumn(format="%.1f °C"),
                "ECMWF-GFS Spread (°C)": st.column_config.NumberColumn(format="%+.1f °C"),
                "Market Implied Temp (°C)": st.column_config.NumberColumn(format="%.1f °C"),
                "Mkt Price of ECMWF Bucket": st.column_config.NumberColumn(format="%.3f"),
                "Mkt Price of GFS Bucket": st.column_config.NumberColumn(format="%.3f"),
                "Mkt Price of ICON Bucket": st.column_config.NumberColumn(format="%.3f"),
                "Mkt Price of National Model Bucket": st.column_config.NumberColumn(format="%.3f"),
                "Favorite Bucket Price": st.column_config.NumberColumn(format="%.3f"),
                "Lead Time (h, to day start)": st.column_config.NumberColumn(format="%.1f"),
                "Hours to Resolution (to day end)": st.column_config.NumberColumn(format="%.1f"),
            },
            use_container_width=True,
            hide_index=True,
        )
        st.caption(
            "**Lead Time** = hours before the target's LOCAL day begins (negative = day already started). "
            "**Hours to Resolution** = hours before that day ENDS, i.e. when the market's outcome is actually "
            "decided — a different, complementary measure. National Model columns are populated only for "
            "Tokyo (JMA), London (UKMO), and Paris (Météo-France)."
        )
        if missing:
            st.caption(
                f"Not shown (not present in this data yet, likely older schema rows): {', '.join(missing)}"
            )

        st.subheader("📊 Model Divergence (ECMWF vs GFS)")
        if has_col(latest, "model_spread_c"):
            fig = px.bar(
                latest,
                x="city",
                y="model_spread_c",
                color="model_spread_c",
                title="ECMWF − GFS (°C). Negative = ECMWF colder than GFS.",
                labels={"model_spread_c": "Model Spread (°C)", "city": "City"},
                color_continuous_scale="RdBu_r",
                color_continuous_midpoint=0,
            )
            st.plotly_chart(fig, use_container_width=True)
        else:
            st.caption("model_spread_c not available for this data.")

        st.subheader("🌡️ Market Implied Temp vs. Each Model")
        base_needed = {"market_implied_temp_c", "ecmwf_max_c", "gfs_max_c"}
        if base_needed.issubset(latest.columns):
            value_vars = ["market_implied_temp_c", "ecmwf_max_c", "gfs_max_c"]
            rename_map = {
                "market_implied_temp_c": "Market Implied",
                "ecmwf_max_c": "ECMWF",
                "gfs_max_c": "GFS",
            }
            if has_col(latest, "icon_max_c"):
                value_vars.append("icon_max_c")
                rename_map["icon_max_c"] = "ICON"
            plot_df = latest.melt(
                id_vars="city",
                value_vars=value_vars,
                var_name="source",
                value_name="temp_c",
            )
            plot_df["source"] = plot_df["source"].map(rename_map)
            fig2 = px.bar(
                plot_df, x="city", y="temp_c", color="source", barmode="group",
                labels={"temp_c": "°C", "city": "City", "source": ""},
            )
            st.plotly_chart(fig2, use_container_width=True)
        else:
            st.caption("Market implied temp not available for this data.")


# ===========================================================================
# TAB: Backtesting
# ===========================================================================
with tab_backtest:
    st.caption(
        "Based only on rows with a confirmed settlement outcome (`ecmwf_hit` "
        "not null). Settlement uses official station data where available "
        "(NOAA/NWS for New York, Chicago, Miami; Hong Kong Observatory for "
        "Hong Kong), an Open-Meteo reanalysis proxy for other cities."
    )

    settled = df[df["ecmwf_hit"].isin([True, False])].copy() if has_col(df, "ecmwf_hit") else pd.DataFrame()

    if settled.empty:
        st.info(
            "No settled rows yet. This is expected right after deployment — "
            "target dates need to actually finish happening before "
            "settle_outcomes.py can determine outcomes."
        )
    else:
        settled["ecmwf_hit"] = settled["ecmwf_hit"].astype(bool)

        col1, col2, col3 = st.columns(3)
        col1.metric("Settled Observations", len(settled))
        col2.metric("ECMWF Bucket Hit Rate", fmt_pct(settled["ecmwf_hit"].mean()))
        unresolved = df["ecmwf_hit"].isna().sum() if has_col(df, "ecmwf_hit") else 0
        col3.metric("Unresolved / Not Yet Settled", int(unresolved))

        st.subheader("Hit Rate by Model Disagreement")
        if has_col(settled, "abs_model_spread_c"):
            spread_bins = [-0.01, 1, 2, 3, float("inf")]
            spread_labels = ["0–1°C", "1–2°C", "2–3°C", "3°C+"]
            settled["spread_bucket"] = pd.cut(
                settled["abs_model_spread_c"], bins=spread_bins, labels=spread_labels
            )
            by_spread = (
                settled.dropna(subset=["spread_bucket"])
                .groupby("spread_bucket", observed=True)["ecmwf_hit"]
                .agg(["mean", "count"])
                .reset_index()
            )
            if not by_spread.empty:
                fig3 = px.bar(
                    by_spread, x="spread_bucket", y="mean",
                    text=by_spread["count"].apply(lambda c: f"n={c}"),
                    labels={"spread_bucket": "|ECMWF − GFS|", "mean": "ECMWF Hit Rate"},
                    title="Does ECMWF's bucket win more/less often when models disagree more?",
                )
                fig3.update_yaxes(tickformat=".0%")
                st.plotly_chart(fig3, use_container_width=True)
            else:
                st.caption("Not enough settled rows with model spread data yet.")
        else:
            st.caption("abs_model_spread_c not available for this data.")

        st.subheader("Hit Rate by Lead Time (hours before the target day BEGINS)")
        st.caption(
            "Standard forecast-verification convention: how far ahead of the target "
            "LOCAL day starting was this observation made. See the next chart for "
            "the complementary 'time to resolution' view."
        )
        if has_col(settled, "lead_time_hours"):
            lt_bins = [-float("inf"), 24, 48, 72, 168, float("inf")]
            lt_labels = ["<24h", "24–48h", "48–72h", "3–7d", "7d+"]
            settled["lead_bucket"] = pd.cut(
                settled["lead_time_hours"], bins=lt_bins, labels=lt_labels
            )
            by_lead = (
                settled.dropna(subset=["lead_bucket"])
                .groupby("lead_bucket", observed=True)["ecmwf_hit"]
                .agg(["mean", "count"])
                .reset_index()
            )
            if not by_lead.empty:
                fig4 = px.bar(
                    by_lead, x="lead_bucket", y="mean",
                    text=by_lead["count"].apply(lambda c: f"n={c}"),
                    labels={"lead_bucket": "Lead Time (to day start)", "mean": "ECMWF Hit Rate"},
                    title="Does ECMWF's bucket accuracy change with lead time?",
                )
                fig4.update_yaxes(tickformat=".0%")
                st.plotly_chart(fig4, use_container_width=True)
            else:
                st.caption("Not enough settled rows with lead time data yet.")
        else:
            st.caption("lead_time_hours not available for this data.")

        st.subheader("Hit Rate by Time to Resolution (hours before the target day ENDS)")
        st.caption(
            "A DIFFERENT question from lead time above: how close was this "
            "observation to the moment the day's actual outcome was fully decided. "
            "A forecast made 6h before the day starts is ~30h before it ends — use "
            "this chart (not the one above) to check whether accuracy sharpens in "
            "the final hours before a market actually resolves."
        )
        if has_col(settled, "hours_to_resolution"):
            rt_bins = [-float("inf"), 6, 24, 48, 96, float("inf")]
            rt_labels = ["<6h", "6-24h", "24-48h", "2-4d", "4d+"]
            settled["resolution_bucket"] = pd.cut(
                settled["hours_to_resolution"], bins=rt_bins, labels=rt_labels
            )
            by_res = (
                settled.dropna(subset=["resolution_bucket"])
                .groupby("resolution_bucket", observed=True)["ecmwf_hit"]
                .agg(["mean", "count"])
                .reset_index()
            )
            if not by_res.empty:
                fig4b = px.bar(
                    by_res, x="resolution_bucket", y="mean",
                    text=by_res["count"].apply(lambda c: f"n={c}"),
                    labels={"resolution_bucket": "Time to Resolution (to day end)", "mean": "ECMWF Hit Rate"},
                    title="Does ECMWF's bucket accuracy sharpen closer to resolution?",
                )
                fig4b.update_yaxes(tickformat=".0%")
                st.plotly_chart(fig4b, use_container_width=True)
            else:
                st.caption("Not enough settled rows with resolution-time data yet.")
        else:
            st.caption("hours_to_resolution not available for this data (older schema rows).")

        st.subheader("Market Calibration: Priced Probability vs. Actual Win Rate")
        st.caption(
            "For rows where the market assigned some price to ECMWF's forecast "
            "bucket, does that price line up with how often it actually won? "
            "Points on the diagonal = well-calibrated market."
        )
        price_col = "ecmwf_bucket_probability" if has_col(settled, "ecmwf_bucket_probability") else (
            "polymarket_price" if has_col(settled, "polymarket_price") else None
        )
        if price_col:
            calib = settled.dropna(subset=[price_col]).copy()
            if len(calib) >= 10:
                calib["price_decile"] = pd.qcut(calib[price_col], q=min(10, calib[price_col].nunique()), duplicates="drop")
                by_decile = (
                    calib.groupby("price_decile", observed=True)
                    .agg(avg_priced=(price_col, "mean"), actual_hit_rate=("ecmwf_hit", "mean"), n=("ecmwf_hit", "count"))
                    .reset_index()
                )
                fig5 = px.scatter(
                    by_decile, x="avg_priced", y="actual_hit_rate", size="n",
                    labels={"avg_priced": "Avg Priced Probability", "actual_hit_rate": "Actual Hit Rate"},
                    title="Calibration Curve",
                )
                fig5.add_shape(
                    type="line", x0=0, y0=0, x1=1, y1=1,
                    line=dict(dash="dash", color="gray"),
                )
                fig5.update_xaxes(tickformat=".0%", range=[0, 1])
                fig5.update_yaxes(tickformat=".0%", range=[0, 1])
                st.plotly_chart(fig5, use_container_width=True)
            else:
                st.caption(f"Only {len(calib)} settled rows with a priced probability — need more data for a calibration curve.")
        else:
            st.caption("No bucket-price column available for calibration.")

        with st.expander("Settled rows (raw)"):
            raw_cols = [c for c in [
                "timestamp_utc", "city", "target_date", "predicted_bucket",
                "ecmwf_bucket_probability", "actual_bucket", "ecmwf_hit",
                "actual_max_c_openmeteo_proxy", "data_quality",
            ] if c in settled.columns]
            st.dataframe(settled[raw_cols], use_container_width=True, hide_index=True)


# ===========================================================================
# TAB: Model Reliability — "which model, which city, which time window"
# ===========================================================================
with tab_reliability:
    st.caption(
        "Pick a city and a date range to see which model has tracked that "
        "city's actual weather most closely, and whether accuracy is "
        "concentrated in a particular window before resolution."
    )

    rel_col1, rel_col2 = st.columns([1, 1])
    with rel_col1:
        rel_city = st.selectbox("City", options=["All Cities"] + all_cities, key="rel_city")
    with rel_col2:
        rel_range_label = st.selectbox(
            "Date range (by target date)",
            options=["Last 3 days", "Last 7 days", "Last 14 days", "Last 30 days", "All time"],
            index=1,
            key="rel_range",
        )

    range_days_map = {"Last 3 days": 3, "Last 7 days": 7, "Last 14 days": 14, "Last 30 days": 30, "All time": None}
    range_days = range_days_map[rel_range_label]

    df_rel = df.copy()
    if range_days is not None and has_col(df_rel, "target_date"):
        parsed = pd.to_datetime(df_rel["target_date"], errors="coerce")
        max_date = parsed.max()
        if pd.notnull(max_date):
            cutoff = max_date - pd.Timedelta(days=range_days - 1)
            df_rel = df_rel[parsed >= cutoff]

    city_arg = None if rel_city == "All Cities" else rel_city
    summary = rb.compute_overall_summary(df_rel, city=city_arg)
    resolution_table = rb.compute_resolution_time_performance(df_rel, city=city_arg)
    daily_table = rb.compute_daily_performance(df_rel, city=city_arg)

    if summary["settled_n"] == 0:
        st.info("No settled observations in this city/date range yet.")
    else:
        # --- Leaderboard cards ---
        rates = {m: summary.get(f"{m}_hit_rate") for m in rb.MODEL_HIT_COLS}
        valid_rates = {m: r for m, r in rates.items() if r is not None}
        best_model = max(valid_rates, key=valid_rates.get) if valid_rates else None

        best_window, best_window_rate = None, None
        if not resolution_table.empty and best_model:
            rc = f"{best_model}_hit_rate"
            if rc in resolution_table.columns:
                valid_windows = resolution_table.dropna(subset=[rc])
                if not valid_windows.empty:
                    row = valid_windows.loc[valid_windows[rc].idxmax()]
                    best_window, best_window_rate = row["resolution_bucket"], row[rc]

        card1, card2, card3 = st.columns(3)
        card1.metric("Best Model", best_model or "—", fmt_pct(valid_rates.get(best_model)) if best_model else None)
        card2.metric("Best Time Window", str(best_window) if best_window else "—",
                     fmt_pct(best_window_rate) if best_window_rate is not None else None)
        card3.metric("Settled Observations", summary["settled_n"])
        st.caption(f"Scope: {rel_city} · {rel_range_label.lower()}")

        # --- Heatmap: model x time-to-resolution window ---
        st.subheader("Hit Rate by Model × Time to Resolution")
        if not resolution_table.empty:
            models = list(rb.MODEL_HIT_COLS.keys())
            buckets = resolution_table["resolution_bucket"].astype(str).tolist()
            z, text = [], []
            for m in models:
                row_z, row_text = [], []
                for _, r in resolution_table.iterrows():
                    rate = r.get(f"{m}_hit_rate")
                    n = r.get(f"{m}_n", 0)
                    if pd.isna(rate):
                        row_z.append(None)
                        row_text.append("—")
                    else:
                        row_z.append(rate * 100)
                        row_text.append(f"{rate*100:.0f}%<br>n={int(n)}")
                z.append(row_z)
                text.append(row_text)
            heatmap_fig = go.Figure(data=go.Heatmap(
                z=z, x=buckets, y=models, text=text, texttemplate="%{text}",
                colorscale="Blues", zmin=0, zmax=100,
                colorbar=dict(title="Hit Rate %"), hoverongaps=False,
            ))
            heatmap_fig.update_layout(
                xaxis_title="Time to Resolution (before target day ends)",
                height=320, margin=dict(t=20, b=20),
            )
            st.plotly_chart(heatmap_fig, use_container_width=True)
            st.caption(
                "Rows = models. Columns = how close to resolution the observation was. "
                "Darker = higher hit rate. '—' means no settled observations in that cell yet."
            )
        else:
            st.caption("Not enough settled data with resolution-time info for a heatmap yet.")

        # --- Trend: best model's hit rate over days in range ---
        st.subheader(f"{best_model or 'Leading model'}'s Hit Rate, Day by Day")
        if best_model and not daily_table.empty:
            rc = f"{best_model}_hit_rate"
            if rc in daily_table.columns:
                trend = daily_table.dropna(subset=[rc])
                if not trend.empty:
                    trend_fig = px.line(
                        trend, x="target_date", y=rc, markers=True,
                        labels={"target_date": "Target Date", rc: "Hit Rate"},
                    )
                    trend_fig.update_yaxes(tickformat=".0%", range=[0, 1])
                    st.plotly_chart(trend_fig, use_container_width=True)
                else:
                    st.caption("Not enough daily data to show a trend yet.")
            else:
                st.caption("No trend data available for this model.")
        else:
            st.caption("Not enough data to identify a leading model yet.")

        with st.expander("Full per-city breakdown (all cities, ignores city filter above)"):
            city_perf = rb.compute_city_performance(df_rel)
            if city_perf.empty:
                st.caption("No settled data in this date range yet.")
            else:
                MIN_CITY_N = 10
                display_perf = city_perf.copy()
                display_perf["Best Model"] = display_perf.apply(
                    lambda r: r["best_model"] if r["n"] >= MIN_CITY_N and pd.notnull(r["best_model"]) else "—",
                    axis=1,
                )
                rate_cols = {f"{m}_hit_rate": f"{m} Hit Rate" for m in rb.MODEL_HIT_COLS}
                perf_table = display_perf[["city", "n", *rate_cols.keys(), "Best Model"]].rename(
                    columns={"city": "City", "n": "Settled n", **rate_cols}
                )
                for m in rb.MODEL_HIT_COLS:
                    col = f"{m} Hit Rate"
                    if col in perf_table.columns:
                        perf_table[col] = perf_table[col] * 100
                st.dataframe(
                    perf_table,
                    column_config={
                        f"{m} Hit Rate": st.column_config.ProgressColumn(
                            f"{m} Hit Rate", format="%.0f%%", min_value=0, max_value=100
                        ) for m in rb.MODEL_HIT_COLS
                    },
                    use_container_width=True,
                    hide_index=True,
                )
                st.caption(f"'Best Model' needs {MIN_CITY_N}+ settled observations for that city; otherwise shown as '—'.")

                city_mae = rb.compute_city_temp_accuracy(df_rel)
                if not city_mae.empty:
                    st.caption("Temperature accuracy (°C mean absolute error) — finer-grained than hit rate:")
                    mae_cols = {c: c.replace("_mae_c", " MAE (°C)").replace("_", " ") for c in city_mae.columns if c.endswith("_mae_c")}
                    mae_table = city_mae[["city", "n", *mae_cols.keys()]].rename(columns={"city": "City", "n": "n", **mae_cols})
                    st.dataframe(mae_table, use_container_width=True, hide_index=True)


# ===========================================================================
# TAB: Data Quality
# ===========================================================================
with tab_quality:
    if has_col(df, "data_quality"):
        dq = df["data_quality"].fillna("UNKNOWN")
        exploded = dq.str.split("|").explode()
        counts = exploded.value_counts().reset_index()
        counts.columns = ["Flag", "Count"]
        col1, col2 = st.columns([1, 2])
        with col1:
            st.dataframe(counts, use_container_width=True, hide_index=True)
        with col2:
            fig6 = px.bar(counts[counts["Flag"] != "OK"], x="Flag", y="Count", title="Data Quality Issues (excluding OK)")
            st.plotly_chart(fig6, use_container_width=True)
    else:
        st.caption("data_quality column not available for this data.")


# ===========================================================================
# TAB: Performance Report
# ===========================================================================
with tab_report:
    st.caption(
        "Generates a day-by-day, lead-time-by-lead-time comparison of ECMWF, "
        "GFS, ICON, each city's national model (where matched), and the "
        "market's own favorite bucket, as a downloadable PNG or Word document "
        "you can share. Built from settled rows only -- descriptive, not a "
        "trading recommendation."
    )

    report_col1, report_col2 = st.columns(2)
    with report_col1:
        report_scope = st.radio(
            "Scope", options=["All Cities Combined", "Single City"], horizontal=True
        )
    report_city = None
    if report_scope == "Single City":
        with report_col2:
            report_city = st.selectbox("Choose city", options=all_cities, key="report_city_select")

    gen_col1, gen_col2 = st.columns(2)
    with gen_col1:
        if st.button("🖼️ Generate PNG Report"):
            png_bytes = rb.build_png_report(df, city=report_city)
            st.session_state["_report_png"] = png_bytes
    with gen_col2:
        if st.button("📝 Generate Word Report"):
            docx_bytes = rb.build_docx_report(df, city=report_city)
            st.session_state["_report_docx"] = docx_bytes

    if "_report_png" in st.session_state:
        st.image(st.session_state["_report_png"], caption="Preview")
        st.download_button(
            "Download PNG",
            data=st.session_state["_report_png"],
            file_name=f"weather_model_report_{(report_city or 'all_cities').replace(' ', '_').lower()}.png",
            mime="image/png",
        )

    if "_report_docx" in st.session_state:
        st.download_button(
            "Download Word Document (.docx)",
            data=st.session_state["_report_docx"],
            file_name=f"weather_model_report_{(report_city or 'all_cities').replace(' ', '_').lower()}.docx",
            mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        )
        st.caption("Word document generated -- preview isn't shown inline, use the download button above.")
